services:
  app:
    image: ussa1976
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ussa1976
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    entrypoint: /bin/bash